---
# Copyright 2020-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
description: 5G RAN Simulator Service
name: 5g-ran-sim
icon: https://guide.opencord.org/logos/cord.svg

version: 2.0.0

- name: prometheus
    version: 15.0.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
