---
# Copyright 2018 Intel Corporation
# Copyright 2018-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
description: OMEC control plane services
name: omec-control-plane
icon: https://guide.opencord.org/logos/cord.svg

version: 0.13.0

dependencies:
  - name: prometheus
    version: 25.7.0  # Use the latest stable version
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
